### PR TITLE
196 fix test for deleting users by meta

### LINKED ISSUE #196: Add tests for Deleting Users by User Meta
Add tests for following filters

Selections

- User Meta

Filters

- Restrict to users who are registered in the site for at least x days
- Restrict to users who don't have any posts in post type

Do this for a couple of post types

### PR DESCRIPTION
**Pull request by anandB000**
Fix #196

### CODE REVIEW

File: tests/wp-unit/tests/include/users/Bulk_Delete_Users_By_User_MetaTest.php [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+
+	/**
+	 * Test basic case of delete users by meta.
+	 */
+	public function test_delete_users_by_meta_without_filters() {
+		//Create one user and set first_name meta to bulk_delete
+		$user = $this->factory->user->create( array( 'user_login' => 'user_test', 'user_pass' => 'ZXC987abc', 'role' => 'subscriber', 'first_name' => 'bulk_delete' ) );
+
+		// Assert that user meta has one user.
+		$users_in_meta = get_users( array( 'meta_key' => 'first_name', 'meta_value' => 'bulk_delete', 'meta_compare' => '=' ) );
```
Comment (sudar) [inline tests/wp-unit/tests/include/users/Bulk_Delete_Users_By_User_MetaTest.php]: You need to add the meta value to the user first before trying to delete users with the meta key.

Otherwise it will always not delete any users.

You need to modify all the test cases.

Comment (anandB000) [reply tests/wp-unit/tests/include/users/Bulk_Delete_Users_By_User_MetaTest.php]: Fixed
