### PR TITLE
331 fix/delete comment meta test

### LINKED ISSUE #331: Delete Comment Meta - Add tests
Add tests for deleting comment meta

Do the following for built-in post type and then separately for a custom post type

- [x] Test deleting comment meta from one comment
- [x] Test deleting comment meta from more than one comment
- [x] Test deleting comment meta from one comment using meta value as well
- [x] Test deleting comment meta from more than one comment using meta value as well
- [x] Test deleting comment meta from more than one comment using meta value as well with different operations.
- [x] Test date filter
- [x] Test deletion in batches
- [ ] Test scheduling of deletion

### PR DESCRIPTION
**Pull request by rajanit2000**
Fix #331

### CODE REVIEW

File: include/Core/Metas/Modules/DeleteCommentMetaModule.php [hunk 1]
```diff
@@ -137,7 +137,14 @@ protected function do_delete( $options ) {
 		}
 
 		if ( $options['use_value'] ) {
-			$args['meta_query'] = apply_filters( 'bd_delete_comment_meta_query', array(), $options );
+			$args['meta_query'] = array(
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteCommentMetaModule.php]: Why have you removed the `apply_filters` call?

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 2]
```diff
@@ -0,0 +1,416 @@
...
+		// Create a post.
+		$post = $this->factory->post->create( array( 'post_title' => 'Test Post' ) );
+
+		$comment_data = array(
+			'comment_post_ID' => $post,
+			'comment_content' => 'Test Comment',
+		);
+
+		// Create a comment.
+		$comment_id = $this->factory->comment->create( $comment_data );
```
Comment (sudar) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: Add one more comment and make sure only one is getting deleted.

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 3]
```diff
@@ -0,0 +1,416 @@
...
+
+		// Create a comment.
+		$comment_id_2 = $this->factory->comment->create( $comment_data );
+
+		add_comment_meta( $comment_id_2, $meta_key, $meta_value );
+
+		// Create a comment.
+		$comment_id_3 = $this->factory->comment->create( $comment_data );
+
+		add_comment_meta( $comment_id_3, $meta_key, $meta_value );
```
Comment (sudar) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: Have at least one comment that will not be deleted.

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 4]
```diff
@@ -0,0 +1,416 @@
...
+		$comment_id = $this->factory->comment->create( $comment_data );
+
+		add_comment_meta( $comment_id, $meta_key, $meta_value );
+
+		// call our method.
+		$delete_options = array(
+			'post_type' => $post_type,
+			'use_value' => false,
+			'meta_key'  => $meta_key,
+			'limit_to'  => -1,
```
Comment (sudar) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: Pass 0 to `limit_to`. Do this in all the places.

**Comment by sudar** [comment]
@rajanit2000 

You have not implemented most of the changes that I told you in the call yesterday.. 

Fix all of those and send it for review again.

**Comment by rajanit2000** [comment]
@sudar Its blocked by the filter register issue
https://github.com/sudar/bulk-delete/blob/1658b127e6d9b4a531e47dbb0aae450b333dcaee/include/Core/Metas/Modules/DeleteCommentMetaModule.php#L42

**Comment by rajanit2000** [comment]
@sudar Its ready to review

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 5]
```diff
@@ -0,0 +1,588 @@
...
+			'comment_post_ID' => $post,
+			'comment_content' => 'Test Comment',
+		);
+
+		// Create a comment.
+		$comment_id = $this->factory->comment->create( $comment_data );
+
+		add_comment_meta( $comment_id, $meta_key, $meta_value );
+
+		add_comment_meta( $comment_id, 'another', 'Another' );
```
Comment (sudar) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: You are using the comment meta value `Another` here and then in `delete_comment_meta` you are checking for `another`.

Store the value in a variable and then use it.

This is happening in lot of test cases. Fix it in all the places.

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 6]
```diff
@@ -0,0 +1,588 @@
...
+		$comments = get_comments( $args );
+
+		$this->assertEquals( $expected['miss_matched'], count( $comments ) );
+
+	}
+
+	/**
+	 * Add to test deleting comment meta older than x days.
+	 */
+	public function test_that_comment_meta_can_be_deleted_olderthan_x_days() {
```
Comment (sudar) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: Change the method name to `test_that_comment_meta_posts_older_than_x_days_can_be_deleted`. Also check the method name format for other test casts as well.

File: include/Core/Metas/Modules/DeleteCommentMetaModule.php [hunk 7]
```diff
@@ -12,6 +12,9 @@
  * @since 6.0.0
  */
 class DeleteCommentMetaModule extends MetasModule {
+	/**
```
[the remark this answers is not in the document]
Comment (rajanit2000) [reply include/Core/Metas/Modules/DeleteCommentMetaModule.php]: Fixed, Now i have removed @since attribute

File: include/Core/Metas/Modules/DeleteCommentMetaModule.php [hunk 8]
```diff
@@ -33,6 +42,9 @@ public function register( $hook_suffix, $page_slug ) {
 		add_filter( 'bd_delete_comment_meta_query', array( $this, 'change_meta_query' ), 10, 2 );
 	}
 
+	/**
+	 * Render the Modules.
```
[the remark this answers is not in the document]
Comment (rajanit2000) [reply include/Core/Metas/Modules/DeleteCommentMetaModule.php]: Update the comment

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php (hunk 5 above)
Comment (rajanit2000) [reply tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: Fixed

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php (hunk 6 above)
Comment (rajanit2000) [reply tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: Fixed

**Comment by rajanit2000** [comment]
@sudar Its ready to review

File: include/Core/Metas/Modules/DeleteCommentMetaModule.php [hunk 9]
```diff
@@ -164,6 +193,13 @@ public function filter_js_array( $js_array ) {
...
 
+	/**
+	 * Get Success Message.
+	 *
+	 * @param int $items_deleted Number of items that were deleted.
+	 *
+	 * @return string Success message.
+	 */
 	protected function get_success_message( $items_deleted ) {
 		/* translators: 1 Number of posts deleted */
```
Comment (rajanit2000) [inline include/Core/Metas/Modules/DeleteCommentMetaModule.php]: Change to number of comment meta deleted

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 10]
```diff
@@ -0,0 +1,600 @@
...
+		$this->assertEquals( 0, count( $comment_meta ) );
+
+		$another_comment_meta = get_comment_meta( $comment_id, $another_meta_key );
+		$this->assertEquals( 1, count( $another_comment_meta ) );
+	}
+
+	/**
+	 * Add to test deleting comment meta from more than one comment using meta value as well.
+	 */
+	public function test_that_comment_meta_can_be_deleted_from_multiple_comment_with_meta_value() {
```
Comment (rajanit2000) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: change to multiple_comments

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 11]
```diff
@@ -0,0 +1,600 @@
...
+			'use_value'    => 1,
+			'meta_key'     => $meta_key,
+			'meta_value'   => $meta_value,
+			'meta_op'      => '=',
+			'meta_type'    => 'CHAR',
+			'limit_to'     => 0,
+			'date_op'      => '',
+			'days'         => 0,
+			'restrict'     => false,
+			'force_delete' => false,
```
Comment (rajanit2000) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: remove `force_delete`

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 12]
```diff
@@ -0,0 +1,600 @@
...
+					),
+				),
+				array(
+					'meta_key'   => 'test_key',
+					'meta_type'  => 'NUMERIC',
+					'meta_value' => '10',
+					'operator'   => '=',
+				),
+				array(
+					'matched'      => '5',
```
Comment (rajanit2000) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: Change to 
`number_of_comments_deleted` and `number_of_comments_not_deleted`

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 13]
```diff
@@ -0,0 +1,600 @@
...
+			array(
+				'post_type' => $post_type,
+			)
+		);
+
+		$comment_data = array(
+			'comment_post_ID' => $post,
+		);
+
+		foreach ( $input as $meta ) {
```
Comment (rajanit2000) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: $meta change to $options

File: tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php [hunk 14]
```diff
@@ -0,0 +1,600 @@
...
+		$comments = get_comments( $args );
+
+		$this->assertEquals( $expected['miss_matched'], count( $comments ) );
+
+	}
+
+	/**
+	 * Add to test deleting comment meta older than x days.
+	 */
+	public function test_that_comment_meta_can_be_deleted_older_than_x_days() {
```
Comment (rajanit2000) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteCommentMetaModuleTest.php]: test_that_comment_meta_can_be_deleted_from_posts_older_than_x_days

**Comment by rajanit2000** [comment]
Find delete comment meta from meta key and value,
Working on it
