### PR TITLE
219 fix/delete posts by tag

### LINKED ISSUE #219: Delete Posts by Tag
## Code
- [x] Create a Metabox to move code to Metaboxes
- [x] Use helper functions if present
- [x] Use helper functions that is mentioned in #204 
- [x] Test all filters manually to make sure the refactoring worked

## Tests
- [x] Modify the existing tests to work in the new architecture.
- [x] Add tests to test deleting posts from All tags
- [x] Add tests to test deleting posts from one tag
- [x] Add tests to test deleting posts from more than one tag
- [x] Add tests to test deleting posts permanently ( at least 2 test cases)
- [x] Add tests to test deleting posts that are older than x days (use at least two categories for this)
- [x] Add tests to test deleting posts that are posted within the last x days (use  at least two categories for this)
- [x] Create more than 100 posts and try to delete them in batches. Test at least 2 batches.
~- [ ] Test that scheduling works by checking if a cron job is scheduled.~ - Will be handled by #229 

@anandB000 

If you have questions, talk to @rajanit2000 or refer to his code. He is working on other metaboxes.

### PR DESCRIPTION
**Pull request by anandB000**
Fix #219

### CODE REVIEW

**Comment by sudar** [comment]
@anandB000 

StyleCI is failing for this PR.

**Comment by sudar** [comment]
This branch is not working. Have you completed the manual testing on this branch?

File: tests/wp-unit/tests/include/Core/Posts/Metabox/DeletePostsByTagTest.php [hunk 1]
```diff
@@ -0,0 +1,413 @@
+<?php
+
+namespace BulkWP\BulkDelete\Core\Posts\Metabox;
+
+use BulkWP\Tests\WPCore\WPCoreUnitTestCase;
+
+/**
+ * Test Deletion of posts by category.
+ *
+ * Tests \BulkWP\BulkDelete\Core\Posts\Metabox\DeletePostsByCategoryMetabox
```
Comment (sudar) [inline tests/wp-unit/tests/include/Core/Posts/Metabox/DeletePostsByTagTest.php]: This comment is outdated.

File: tests/wp-unit/tests/include/Core/Posts/Metabox/DeletePostsByTagTest.php [hunk 2]
```diff
@@ -0,0 +1,413 @@
...
+ *
+ * @since 6.0.0
+ */
+class DeletePostsByTagTest extends WPCoreUnitTestCase {
```
Comment (sudar) [inline tests/wp-unit/tests/include/Core/Posts/Metabox/DeletePostsByTagTest.php]: The name of this class should be `DeletePostsByTagMetaboxTest`
