### PR TITLE
247 fix/delete term meta

### LINKED ISSUE #247: Add the ability to delete Term meta
- [x] Add a new module called `Delete Term Meta` in the `Delete Meta Fields` page.
- [x] Show a list of available taxonomies. Use single select dropdown for this. Create a render method in `Renderer` if nothing is available already.
- [x] Once the user chooses the taxonomy, show the list of terms associated with that taxonomy. Use multi-select dropdown for this. Create a render method in `Renderer` if nothing is available already.
- [x] Show a list a unique meta keys for the taxonomy. Use a single select dropdown. Create a helper function in `Fetcher` to get the list of unique keys. Create a helper method in `Renderer` class to render this dropdown
- [x] Show a list of operations in a single select dropdown. Possible options are the following. We can add more later.
a) Equals to
b) Not Equals to
- [x] Add a textbox to enter the values.
- [x] Use Term Meta Query to retrieve the terms and then loop over them to delete the term meta data.

PR: https://github.com/sudar/bulk-delete/pull/445

### PR DESCRIPTION
**Pull request by rajanvijayan**
Fix #247

### CODE REVIEW

**Comment by rajanit2000** [comment]
Development is done, Waiting for review

File: assets/js/src/delete-term-meta.js [hunk 1]
```diff
@@ -0,0 +1,72 @@
+/**
+ * Add select2 functionality..
+ */
+ /*global ajaxurl*/
+jQuery( document ).ready( function () {
+	
+	jQuery( 'input[name=smbd_meta_term_taxonomy]' ).change(function(){
+		jQuery( '.select2-terms' ).select2( {
```
Comment (sudar) [inline assets/js/src/delete-term-meta.js]: Don't use the class name `select2`. It is causing issues.

Rename it to `enhanced-terms-dropdow`

File: include/Core/Base/Mixin/Fetcher.php [hunk 2]
```diff
@@ -22,6 +22,10 @@ protected function get_post_types() {
 		return bd_get_post_types();
 	}
 
+	protected function get_taxonomies() {
```
Comment (sudar) [inline include/Core/Base/Mixin/Fetcher.php]: Add PHPDoc block comment for this method.

Basically if the method is not a inherited method then you have to add comments.

File: include/Core/Controller.php [hunk 3]
```diff
@@ -164,6 +165,31 @@ public function load_taxonomy_term() {
 		die;
 	}
 
+	/**
+	 * Ajax call back function for getting taxonomies meta to load select2 options.
+	 *
+	 * @since 6.0.1
```
Comment (sudar) [inline include/Core/Controller.php]: Change this to 6.0.0

File: include/Core/Controller.php [hunk 4]
```diff
@@ -164,6 +165,31 @@ public function load_taxonomy_term() {
...
+	 */
+	public function load_taxonomy_term_meta() {
+		$response = array();
+
+		$term_id = sanitize_text_field( $_GET['term_id'] );
```
Comment (sudar) [inline include/Core/Controller.php]: Use `absint` function instead of `sanitize_text_field`

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 5]
```diff
@@ -0,0 +1,176 @@
...
+namespace BulkWP\BulkDelete\Core\Metas\Modules;
+
+use BulkWP\BulkDelete\Core\Metas\MetasModule;
+
+defined( 'ABSPATH' ) || exit; // Exit if accessed directly.
+
+/**
+ * Delete Term Meta.
+ *
+ * @since 6.1.0
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php:11]: Change to 6.0.0

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+			'box_label'  => __( 'Bulk Delete Term Meta', 'bulk-delete' ),
+			'scheduled'  => __( 'Term meta fields from the posts with the selected criteria are scheduled for deletion.', 'bulk-delete' ),
+			'cron_label' => __( 'Delete Term Meta', 'bulk-delete' ),
+		);
+	}
+
+	/**
+	 * Render the Modules.
+	 *
+	 * @return void
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Don't add phpdoc block for inherited methods.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+		}
+		?>
+		</table>
+
+		<h4><?php _e( 'Choose your term want to delete', 'bulk-delete' ); ?></h4>
+		<table class="optiontable">
+			<tr>
+				<td>
+					<select class="select2 select2-terms" name="smbd_<?php echo esc_attr( $this->field_slug ); ?>_term">
+						<option>Choose Terms</option>
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: This text should be made available for translation.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 8]
```diff
@@ -0,0 +1,176 @@
...
+					</select>
+				</td>
+			</tr>
+		</table>
+
+		<h4><?php _e( 'Choose your term meta want to delete', 'bulk-delete' ); ?></h4>
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Change to `Select the term meta that you want to delete`

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 9]
```diff
@@ -0,0 +1,176 @@
...
+		<table class="optiontable">
+			<tr>
+				<td>
+					<select class="select2 select2-term-meta" name="smbd_<?php echo esc_attr( $this->field_slug ); ?>_term_meta">
+						<option>Choose Term Meta</option>
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Make this text available for translation by wrapping inside `_e` function. Do it for all other strings.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 10]
```diff
@@ -0,0 +1,176 @@
...
+				</td>
+			</tr>
+		</table>
+
+		<?php
+		/**
+		 * Add more fields to the delete post meta field form.
+		 * This hook can be used to add more fields to the delete post meta field form.
+		 *
+		 * @since 5.4
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Looks like you copy pasted and didn't change.

Replace post meta with term meta and change 5.4 to 6.0.0

File: include/ui/form.php [hunk 11]
```diff
@@ -198,6 +198,12 @@ function bd_get_post_types() {
 	return array_merge( $builtin_types, $custom_types );
 }
 
+function bd_get_taxonomies(){
```
Comment (sudar) [inline include/ui/form.php]: If the function is going to only call `get_taxonomies` then directly use it. Don't create a new function for it.

**Review by sudar — CHANGES_REQUESTED** [review]

File: assets/js/src/delete-term-meta.js (hunk 1 above)
Comment (rajanvijayan) [reply assets/js/src/delete-term-meta.js]: Fixed

File: include/Core/Base/Mixin/Fetcher.php (hunk 2 above)
Comment (rajanvijayan) [reply include/Core/Base/Mixin/Fetcher.php]: Fixed

File: include/Core/Controller.php (hunk 3 above)
Comment (rajanvijayan) [reply include/Core/Controller.php]: Fixed

File: include/Core/Controller.php (hunk 4 above)
Comment (rajanvijayan) [reply include/Core/Controller.php]: Fixed

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 5 above)
Comment (rajanvijayan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php:11]: Fixed

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 6 above)
Comment (rajanvijayan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: Fixed

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 7 above)
Comment (rajanvijayan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: Fixed

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 8 above)
Comment (rajanvijayan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: Fixed

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 9 above)
Comment (rajanvijayan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: Fixed

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 10 above)
Comment (rajanvijayan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: Fixed

File: include/Core/Controller.php [hunk 12]
```diff
@@ -164,6 +165,31 @@ public function load_taxonomy_term() {
 		die;
 	}
 
+	/**
+	 * Ajax call back function for getting taxonomies meta to load select2 options.
+	 *
+	 * @since 6.0.0
+	 */
+	public function load_taxonomy_term_meta() {
```
[the remark this answers is not in the document]
Comment (rajanit2000) [reply include/Core/Controller.php]: @sudar How can i fix this issue? I have fix all rest of changes

File: include/Core/Base/Mixin/Fetcher.php [hunk 13]
```diff
@@ -22,6 +22,17 @@ protected function get_post_types() {
 		return bd_get_post_types();
 	}
 
+	/**
+	 * Get the list of taxompmies registered in WordPress.
+	 *
+	 * @return A list of taxonomy names
+	 */
+	protected function get_taxonomies() {
```
Comment (sudar) [inline include/Core/Base/Mixin/Fetcher.php]: If you are only going to be calling `get_taxonomies` function, then there is no need for this function.

Remove it and use `get_taxonomies` directly.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 14]
```diff
@@ -0,0 +1,174 @@
...
+		?>
+		<!-- Term Meta box start-->
+		<fieldset class="options">
+		<?php
+		$taxonomies = $this->get_taxonomies();
+		?>
+		<h4><?php _e( 'Select the taxonomy whose term meta fields you want to delete', 'bulk-delete' ); ?></h4>
+		<table class="optiontable">
+		<?php
+		foreach ( $taxonomies as $taxonomy ) {
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Use the `render_taxonomy_dropdown` method to render the taxonomies.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 15]
```diff
@@ -0,0 +1,174 @@
...
+		 * This hook can be used to add more fields to the delete term meta field form.
+		 *
+		 * @since 6.0.0
+		 */
+		do_action( 'bd_delete_term_meta_form' );
+		?>
+
+		</fieldset>
+
+		<p>
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Use the `render_submit_button` helper function to get the submit button.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 16]
```diff
@@ -0,0 +1,174 @@
...
+	 *
+	 * @param array $request Request array.
+	 * @param array $options User options.
+	 *
+	 * @return array User options.
+	 */
+	protected function convert_user_input_to_options( $request, $options ) {
+		$options['term'] = esc_sql( bd_array_get( $request, 'smbd_' . $this->field_slug . '_term', 'term' ) );
+
+		$options['term_meta']       = bd_array_get( $request, 'smbd_' . $this->field_slug . '_term_meta', 'term_meta' );
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Call `sanitize_text_field` function on the user input.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 17]
```diff
@@ -0,0 +1,174 @@
...
+	 * Delete action.
+	 *
+	 * @param array $options User options.
+	 */
+	public function do_delete( $options ) {
+		$count = 0;
+
+		if ( 'equal' === $options['term_meta_option'] ) {
+			$is_delete = delete_term_meta( $options['term'], $options['term_meta'], $options['term_meta_value'] );
+			if ( $is_delete ) {
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Call this variable `$is_deleted`

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 18]
```diff
@@ -0,0 +1,174 @@
...
+				$count++;
+			}
+		} elseif ( 'not_equal' === $options['term_meta_option'] ) {
+			$term_value = get_term_meta( $options['term'], $options['term_meta'], true );
+			if ( $term_value !== $options['term_meta_value'] ) {
+				delete_term_meta( $options['term'], $options['term_meta'] );
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Check the return value of `delete_term_meta` before incrementing the `count` variable.

**Review by sudar — CHANGES_REQUESTED** [review]

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 16 above)
Comment (rajanvijayan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: @sudar how to use this method?

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 17 above)
Comment (sudar) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: @rajanit2000 

The variable name should be `$is_deleted` not `$is_delete`

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 19]
```diff
@@ -0,0 +1,167 @@
...
+	/**
+	 * Filter JS Array and add pro hooks.
+	 *
+	 * @param array $js_array JavaScript Array.
+	 *
+	 * @return array Modified JavaScript Array.
+	 */
+	public function filter_js_array( $js_array ) {
+		$js_array['dt_iterators'][]                 = '_' . $this->field_slug;
+		$js_array['validators']['delete_meta_term'] = 'noValidation';
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Instead of hardcoding `delete_meta_term`, use `$this->action`

File: include/Core/Metas/Modules/DeleteTermMetaModule.php [hunk 20]
```diff
@@ -0,0 +1,167 @@
...
+
+	/**
+	 * Get Success Message.
+	 *
+	 * @param int $items_deleted Number of items that were deleted.
+	 *
+	 * @return string Success message.
+	 */
+	protected function get_success_message( $items_deleted ) {
+		/* translators: 1 Number of posts deleted */
```
Comment (sudar) [inline include/Core/Metas/Modules/DeleteTermMetaModule.php]: Copy/paste error. Comment is not updated.

File: tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php [hunk 21]
```diff
@@ -0,0 +1,184 @@
...
+	public function setUp() {
+		parent::setUp();
+
+		$this->module = new DeleteTermMetaModule();
+	}
+
+	/**
+	 * Add to test delete default taxonomy term meta with equal value.
+	 */
+	public function test_that_term_meta_can_be_deleted_with_default_taxonomy_in_equal_value() {
```
Comment (sudar) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php]: Rename to `test_that_term_meta_can_be_deleted_from_default_taxonomy_using_equal_operator.

Change the other function also to follow the correct format.

File: tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php [hunk 22]
```diff
@@ -0,0 +1,184 @@
...
+		$delete_options = array(
+			'term'             => $term_array['term_id'],
+			'term_meta'        => $meta_key,
+			'term_meta_value'  => $matched_meta_value,
+			'term_meta_option' => 'equal',
+		);
+
+		$meta_deleted = $this->module->delete( $delete_options );
+
+		// Assert that post meta deleted.
```
Comment (sudar) [inline tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php]: Another copy/paste error. Check the comment.

**Review by sudar — CHANGES_REQUESTED** [review]

**Comment by sudar** [comment]
@rajanit2000 

I am still seeing lot of copy/paste errors.

Are you doing a self review before submitting for PR?

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 19 above)
Comment (esudalaimadan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: Fixed.

File: include/Core/Metas/Modules/DeleteTermMetaModule.php (hunk 20 above)
Comment (esudalaimadan) [reply include/Core/Metas/Modules/DeleteTermMetaModule.php]: Fixed.

File: tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php (hunk 21 above)
Comment (esudalaimadan) [reply tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php]: Fixed.

File: tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php (hunk 22 above)
Comment (esudalaimadan) [reply tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php]: Fixed.

**Comment by sudar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- include/Core/Metas/Modules/DeleteTermMetaModule.php  7
- assets/js/src/delete-term-meta.js  2
- tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php  1
         

Clones added
============
- assets/js/src/delete-term-meta.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/bulk-delete/bulk-delete/pullRequest?prid=1939930&bid=8119203)

File: include/Core/Controller.php [hunk 23]
```diff
@@ -161,6 +162,31 @@ public function load_taxonomy_term() {
...
```
Comment (sudar) [inline include/Core/Controller.php]: Codacy Issue found: [load_taxonomy_term_meta accesses the super-global variable $_GET.](https://app.codacy.com/app/BulkWP/bulk-delete/pullRequest?prid=1939930)

**Comment by sudar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- include/Core/Metas/Modules/DeleteTermMetaModule.php  7
- assets/js/src/delete-term-meta.js  2
- tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php  1
         

Clones added
============
- assets/js/src/delete-term-meta.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/bulk-delete/bulk-delete/pullRequest?prid=1939930&bid=8119203)

File: include/Core/Controller.php (hunk 23 above)
Comment (sudar) [inline include/Core/Controller.php]: Codacy Issue found: [load_taxonomy_term_meta accesses the super-global variable $_GET.](https://app.codacy.com/app/BulkWP/bulk-delete/pullRequest?prid=1939930)

**Comment by sudar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- assets/js/src/delete-term-meta.js  2
- include/Core/Metas/Modules/DeleteTermMetaModule.php  7
- tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php  1
         

Clones added
============
- assets/js/src/select2.js  2
- assets/js/src/delete-term-meta.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/bulk-delete/bulk-delete/pullRequest?prid=1939930&bid=8119203)

File: include/Core/Controller.php [hunk 24]
```diff
@@ -161,6 +162,31 @@ public function load_taxonomy_term() {
 		die;
 	}
 
+	/**
+	 * Ajax call back function to load term meta by term.
+	 *
+	 * @since 6.1.0
+	 */
+	public function load_term_metas() {
```
Comment (sudar) [inline include/Core/Controller.php]: Codacy Issue found: [load_term_metas accesses the super-global variable $_GET.](https://app.codacy.com/app/BulkWP/bulk-delete/pullRequest?prid=1939930)

File: include/Core/Controller.php [hunk 25]
```diff
@@ -131,11 +132,11 @@ public function verify_get_request_nonce( $result, $action ) {
 	}
 
 	/**
-	 * Ajax call back function for getting taxonomies to load select2 options.
+	 * Ajax call back function to load taxonomy terms by taxonomy.
 	 *
 	 * @since 6.0.0
 	 */
-	public function load_taxonomy_term() {
+	public function load_taxonomy_terms() {
```
Comment (sudar) [inline include/Core/Controller.php]: Codacy Issue found: [load_taxonomy_terms accesses the super-global variable $_GET.](https://app.codacy.com/app/BulkWP/bulk-delete/pullRequest?prid=1939930)

**Comment by sudar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- assets/js/src/delete-term-meta.js  2
- include/Core/Metas/Modules/DeleteTermMetaModule.php  7
- tests/wp-unit/include/Core/Metas/Modules/DeleteTermMetaModuleTest.php  1
         

Clones added
============
- assets/js/src/select2.js  1
- assets/js/src/delete-term-meta.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/bulk-delete/bulk-delete/pullRequest?prid=1939930&bid=8119203)

File: include/Core/Controller.php (hunk 25 above)
Comment (sudar) [inline include/Core/Controller.php]: Codacy Issue found: [load_taxonomy_terms accesses the super-global variable $_GET.](https://app.codacy.com/app/BulkWP/bulk-delete/pullRequest?prid=1939930)

File: include/Core/Controller.php [hunk 26]
```diff
@@ -161,6 +162,45 @@ public function load_taxonomy_term() {
 		die;
 	}
 
+	/**
+	 * Ajax call back function to load term meta by term.
+	 *
+	 * @since 6.1.0
+	 */
+	public function load_term_metas() {
```
Comment (sudar) [inline include/Core/Controller.php]: Codacy Issue found: [load_term_metas accesses the super-global variable $_GET.](https://app.codacy.com/app/BulkWP/bulk-delete/pullRequest?prid=1939930)

**Review by sudar — APPROVED** [review]
