### PR TITLE
Plugin page crashes if there are huge number of taxonomies

### LINKED ISSUE #194: Plugin page crashes if there are huge number of tags or categories
We should not try to load all the tags/categories.

Requested at https://bulkwp.com/support/topic/bulk-delete-posts-page-timeout/

### PR DESCRIPTION
**Pull request by rajanit2000**
Fix #194

### CODE REVIEW

File: assets/js/src/bulk-delete.js [hunk 1]
```diff
@@ -13,6 +13,37 @@ jQuery(document).ready(function () {
...
+	jQuery( '.select2Ajax' ).select2({
+		ajax: {
+    			url: ajaxurl, 
+    			dataType: 'json',
+    			delay: 250, 
+    			data: function (params) {
+    				var term = jQuery(this).attr('data-term');
+      				return {
+        				q: params.term, 
+        				term: term,
```
Comment (sudar) [inline assets/js/src/bulk-delete.js]: This is actually the taxonomy. So change the variable and object key to `taxonomy` to make it more readable.

File: bulk-delete.php [hunk 2]
```diff
@@ -441,6 +448,28 @@ public function add_delete_posts_settings_panel() {
...
+	/**
+	 * Ajax call back function for getting taxonomies to load select2 options.
+	 *
+	 * @since 5.7.0
+	 */
+	public function load_taxonomy_term(){
+		$return = array();
+
+		$terms = get_terms( array(
+			'taxonomy' => $_GET['term'],
```
Comment (sudar) [inline bulk-delete.php]: Change the post variable to `taxonomy`, since it is actually a taxonomy and not term.

File: bulk-delete.php [hunk 3]
```diff
@@ -441,6 +448,28 @@ public function add_delete_posts_settings_panel() {
...
+			'hide_empty' => false,
+			'search' => $_GET['q']
```
Comment (sudar) [inline bulk-delete.php]: User input values are not sanitized. This could cause a security issue.

File: bulk-delete.php [hunk 4]
```diff
@@ -441,6 +448,28 @@ public function add_delete_posts_settings_panel() {
...
+		) );
+
+		foreach ( $terms as $term ) {
```
Comment (sudar) [inline bulk-delete.php]: `get_terms` can return `WP_Error`. Make sure that case is also handled.

File: bulk-delete.php [hunk 5]
```diff
@@ -441,6 +448,28 @@ public function add_delete_posts_settings_panel() {
 		wp_enqueue_script( 'postbox' );
 	}
 
+	/**
+	 * Ajax call back function for getting taxonomies to load select2 options.
+	 *
+	 * @since 5.7.0
+	 */
+	public function load_taxonomy_term(){
+		$return = array();
```
Comment (sudar) [inline bulk-delete.php]: Change the variable name `$return` to something that is more readable like `payload` or `response`.

File: include/posts/class-bulk-delete-posts.php [hunk 6]
```diff
@@ -212,12 +212,18 @@ public static function render_delete_posts_by_category_box() {
         <table class="form-table">
             <tr>
                 <td scope="row">
-				<select class="select2" name="smbd_cats[]" multiple data-placeholder="<?php _e( 'Select Categories', 'bulk-delete' ); ?>">
-					<option value="all"><?php _e( 'All Categories', 'bulk-delete' ); ?></option>
-		<?php foreach ( $categories as $category ) { ?>
-			<option value="<?php echo $category->cat_ID; ?>"><?php echo $category->cat_name, ' (', $category->count, ' ', __( 'Posts', 'bulk-delete' ), ')'; ?></option>
-		<?php } ?>
+                <?php if( count($categories) > 50 ){?>
+					<select class="select2Ajax" name="smbd_cats[]" data-term="category" multiple data-placeholder="<?php _e( 'Select Categories', 'bulk-delete' ); ?>" style="width:300px">
```
Comment (sudar) [inline include/posts/class-bulk-delete-posts.php]: The attribute `data-term` should be `data-taxonomy`. This is applicable for tags as well.

**Comment by sudar** [comment]
@rajanit2000 

On the whole the code looks good. I also like the fact that you choose to have a single AJAX request for both tags and categories.

I have left a couple of code review comments. Go over them and fix them.

Also a couple of workflow related things.

- Some of the style checks are failing. They are reported near the `merge` button. Click the link to find those issues.
- The commit message should talk about what is being done. See the link at https://github.com/sudar/bulk-wp-site/wiki/Workflow#git-commit-messages
- When there are more than 50 tags/categories, the default option All Tags/All Categories is getting removed
